### ISSUE TITLE
Building library in custom path

### ISSUE THREAD

**Issue by lukne541** [apoelstra/secp256k1-zkp#16]
How do I install the .a,.o,.so etc files at a custom location? 
Thanks,
L

**Comment by apoelstra** [comment]
I think this is what you want https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Installation-Directory-Variables.html

but honestly I'm not sure. We use autotools which is something of a black box to me.

**Comment by apoelstra** [comment]
Actually, people on IRC suggest `./configure —prefix=wherever_you_want_stuff_installed`

**Comment by lukne541** [comment]
That worked, thanks for the help!
