### ISSUE TITLE
Bulletproof for multisig commitment

### ISSUE THREAD

**Issue by jaspervdm** [apoelstra/secp256k1-zkp#5]
Given a commitment `C=x1G+x2G+vH`, constructed by 2 participants that each only know one of the blinding factors and `v`, would it be possible for both of them to generate some kind of a partial bulletproof, which can then be aggregated by either of them to produce a single bulletproof for `C`?

**Comment by apoelstra** [comment]
Yes.

**Comment by jaspervdm** [comment]
So I've done some thinking, and came up with the following scheme (using the BP paper notation):
* The total commit is `V=h^(ga_A) h^(ga_B) g^v` with `ga_A, ga_B` the secret key belonging to party A, B respectively
* Party B generates `tau_1B, tau_2B` and sends `h^(tau_1B)` and `h^(tau_2B)` along with `tau_xB=tau_2B x^2 + tau_1B x + z^2 ga_B` (with the same `x` and `z` as the original calculation)
* Party A generates their own `tau_1A, tau_2A` and calculates `T_i = g^(t_i) h^(tau_i A) h^(tau_i B)` for `i=1,2` and `tau_xA` from which it calculates `tau_x = tau_xA + tau_xB`
* From this party A can do the full BP calculation, where all other formulas are exactly the same as the original method

Do you think this method will work? Or did I miss something obvious? Thanks a lot!

Edit: there are some things missing from these steps, but I think the general gist is correct. I managed to create valid bulletproofs. If anyone is interested on how I did it, here is the code: https://github.com/mimblewimble/secp256k1-zkp/compare/testnet3...jaspervdm:bp_multisig
